### ISSUE TITLE
I feel like there is something missing in the README file

### ISSUE THREAD

**Issue by hagronnestad** [garytm/EarthquakeApp#2]
Please take a look at my pull request (#1) and consider merging it. T<sub>ha<sup>n</sup></sub><sub>k</sub>s

**Comment by garytm** [comment]
Thank for help. Good

**Comment by hagronnestad** [comment]
So, where's the merge? 🤔

**Comment by garytm** [comment]
U send PayPal. Merge ok

**Comment by hagronnestad** [comment]
I give up.
